baselogic/urls.py
from django.urls import path
from baselogic import views as handler


urlpatterns = [
    path('sendmail/', handler.FormHendler.as_view(), name='sendmail'),
    path('sendreview/',handler.SendReviewView.as_view(), name='sendreview'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('handler/', include('baselogic.urls')),
    # path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




admin.site.site_title = 'TMV'
admin.site.site_header = 'TMV CMS'
admin.site.index_title = "Welcome from Vitalik"

baselogic/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class UserMailLog(models.Model):
    sendername = models.CharField("Отправитель", max_length=99, default='', blank=False, null=False)
    sendermail = models.EmailField("Адрес отправителя", max_length=155, default='', blank=False, null=False)
    mailtext = models.CharField("Текст письма", max_length=999, default='', blank=False, null=False)
    sendtime = models.DateTimeField("Время отправления", default=timezone.datetime.now, blank=False, null=False)

    def __str__(self):
        return f'от {self.sendermail}'

content/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from allauth.socialaccount.models import SocialAccount, SocialApp

# Create your models here.
from PIL import Image
from io import BytesIO
import requests, os


class CarouselItem(models.Model):
    title = models.CharField("Заголовок", max_length=25, null=False, blank=False, default='ItemHeader')
    description = models.CharField("Описание", max_length=50, null=False, blank=False, default="Base description")
    image = models.ImageField("Картинка" ,default='classic.jpg', null=False, upload_to='carouselfiles')
    delay = models.CharField("Зависание", max_length=3, default='400', null=False)
    active = models.BooleanField(default=True, null=False)

    class Meta:
        verbose_name = 'Сервис'
        verbose_name_plural = 'Сервисы'


    def __str__(self):
        return f'-- {self.title} --'

    def get_active_items():
        return CarouselItem.objects.filter(active=True)

    def save(self):
        super().save()
        with Image.open(self.image.path) as item:
            if item.height > 0 or item.width > 0:
                size = (600, 400)
                im = item.resize(size, Image.ANTIALIAS)
                im.save(self.image.path)


class UserReview(models.Model):
    uploadto = 'socialuser'

    sendername = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='Отправитель'
    )
    review = models.TextField("Отзыв", max_length=999, null=False, blank=False)
    create_date = models.DateTimeField("Написан", default=timezone.datetime.now)
    is_moderate = models.BooleanField("Отображать", default=False)
    avatar = models.ImageField("Ава соцсети", default='def.jpg', null=True, blank=True, upload_to=uploadto)


    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'

    #   FUNCTIONS
    def getUserAvas(self):
        urlpath = ''
        try:
            t = SocialAccount.objects.get(user_id=self.sendername_id) # change to self.sendername_id
            # TODO: add for VK, Facebook, ...
            provideravas = ['picture', 'avatar_url']
            for _ in provideravas:
                if _ in t.extra_data:
                    urlpath = t.extra_data.get(_)
        except ObjectDoesNotExist as e:
            print(e)

        print(urlpath)
        if urlpath:
            try:
                resp = requests.get(urlpath, timeout=4.0)
                print(resp.status_code)
                ext = '.' + resp.headers.get('Content-Type').split('/')[-1]

                filename = self.sendername.username + '(' + timezone.datetime.now().strftime('%d%m%y-%H%M%S') + ')' + ext
                filedir = os.path.join(
                    os.path.dirname(self.avatar.path),
                    self.uploadto,
                )

                filepath = os.path.join(filedir, filename)

                with Image.open(BytesIO(resp.content)) as img:
                    img.save(filepath)
                    self.avatar = os.path.join(self.uploadto, filename)
            except:
                print('!'*50)


    def __str__(self):
        return f"Отзыв от {self.sendername}"


    def save(self):
        self.getUserAvas()
        super().save()

content/forms.py
from django import forms

#################
from .models import UserReview



class ReviewForm(forms.ModelForm):
    class Meta:
        model = UserReview
        fields = ('sendername', 'review')

baselogic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils import timezone

# Create your views here.
from baselogic.models import UserMailLog
from content.models import UserReview
from content.forms import ReviewForm
from config.settings import DEFAULT_FROM_EMAIL


class FormHendler(View):
    def post(self, request):
        subject = 'Сообщение от {} c {}'.format(request.POST.get('cf-name', ''), request.POST.get('cf-email', ''))
        message = request.POST.get('cf-message', '')
        from_email = DEFAULT_FROM_EMAIL
        if subject and message and from_email:
            try:
                maillog = UserMailLog()
                maillog.sendername = subject
                maillog.sendermail = request.POST.get('cf-email', '')
                maillog.mailtext = message
                maillog.save()
                # change mail iin list to owner mail
                send_mail(subject, message, from_email, ['yurevich_vital@mail.ru'], fail_silently=False)
            except BadHeaderError:
                messages.add_message(request, messages.INFO, 'Invalid header found.')
                return redirect('/')
            messages.add_message(request, messages.INFO, 'Сообщение отправлено.')
        return HttpResponseRedirect('/')


class SendReviewView(View):
    def post(self, request):
        review = ReviewForm(request.POST)
        if review.is_valid():
            review.save(commit=False)
            review.save()
            messages.add_message(request, messages.INFO, 'Ваш отзыв отправлен. Спасибо.')
        else:
            try:
                obj = UserReview.objects.get(sendername_id=request.user.id)
                obj.review = request.POST.get('review')
                obj.is_moderate = False
                obj.create_date = timezone.datetime.now()
                obj.save()
                messages.add_message(request, messages.INFO, 'Ваш отзыв изменен. Спасибо.')
            except:
                print('error')

        return redirect('/')

content/views.py
from django.shortcuts import render

# Create your views here.

templates/base_tmpl.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>

     <title>{% block title %}{% endblock %}</title>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Another meta for shares -->
    <meta property="relap:enabled" content="1">
    <meta property="relap:version" content="v7">
    <meta property="og:type" content="article">
    <meta property="og:title" content="Ремонт и настройка Ваших устройств">
    <meta property="og:description" content="Ремонт и настройка Ваших устройств">
    <meta property="og:url" content="http://tmv.by/">
    <meta property="og:locale" content="ru_RU">
    <meta property="og:image" content="http://tmv.by/static/imgsite.jpg" />
    <meta property="og:image:secure_url" content="https://tmv.by/static/imgsite.jpg" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:width" content="968" />
    <meta property="og:image:height" content="504" />
    <meta property="og:image:alt" content="Ремонт и настройка Ваших устройств" />
    <meta property="og:site_name" content="TMV.BY">

     <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
     <link rel="stylesheet" href={% static "css/font-awesome.min.css" %}>
     <link rel="stylesheet" href={% static "css/aos.css" %}>

    {#     OWL CAROUSEL CSS    #}
     <link rel="stylesheet" href={% static "css/owl.carousel.min.css" %}>
     <link rel="stylesheet" href={% static "css/owl.theme.default.min.css" %}>

     <!-- MAIN CSS -->
     <link rel="stylesheet" href={% static "css/tmv-base-style.css" %}>

     <!-- Social shares -->
     <script type="text/javascript" src="https://vk.com/js/api/share.js?95" charset="windows-1251"></script>
     <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v8.0" nonce="5L6LvEw1"></script>

     <!-- AWESOME kit -->
     <script src="https://kit.fontawesome.com/a6f186b029.js" crossorigin="anonymous"></script>
</head>

<body data-spy="scroll" data-target="#navbarNav" data-offset="50">

{% block content %}{% endblock %}

</body>
</html>

templates/flat/index.html
{% extends 'base_tmpl.html' %}
{% load static content_tags %}

{% block title %}
    TonerMaster {% if user.is_authenticated %}| {{ user }} {% endif %}
{% endblock %}


{#<body data-spy="scroll" data-target="#navbarNav" data-offset="50">#}
{% block content %}

{#    <!-- include sitemenu -->#}
    {% include 'flat/navbar.html' %}

    {% if user.is_authenticated %}
{#        include modal exit form       #}

        {% include 'flat/modal_logout.html' %}
        {% include 'flat/modal_review.html' %}

    {% else %}
{#     include modal -->#}
    {% include 'flat/modal_auth.html' %}
{#    <!-- include signup modal form -->    #}
    {% include 'flat/modal_signup.html' %}
    {% endif %}

     <!-- HERO -->
    <section class="hero d-flex flex-column justify-content-center align-items-center" id="home">

        <div class="bg-overlay"></div>

        <div class="container">
        {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-primary alert-dismissible fade show" role="alert" data-aos="fade-up" data-aos-delay="200">
                            {{message}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            <div class="row">

                <div class="col-lg-8 col-md-10 mx-auto col-12">
                    <div class="hero-text mt-3 text-center">

                        <h6 data-aos="fade-up" data-aos-delay="300">Мы оказываем широкий спектр услуг</h6>

                        <h1 class="text-white" data-aos="fade-up" data-aos-delay="500">по  заправке картриджей, ремонту и настройке ваших устройств</h1>
                        {% if not user.is_authenticated %}
                            <a href="#" class="btn custom-btn mt-3" data-aos="fade-up" data-aos-delay="900" data-toggle="modal" data-target="#signupForm">Регистрация</a>
                            {#                                    <a href="#feature" class="btn custom-btn mt-3" data-aos="fade-up" data-aos-delay="600">Get started</a>#}
                            <a href="#" class="btn custom-btn bordered mt-3" data-aos="fade-up" data-aos-delay="800" data-toggle="modal" data-target="#signinForm">Авторизация</a>
                            {#                                    <a href="#about" class="btn custom-btn bordered mt-3" data-aos="fade-up" data-aos-delay="700">learn more</a>#}
                        {% else %}
                            <a href="#" class="btn custom-btn bordered mt-3" data-aos="fade-up" data-aos-delay="800" data-toggle="modal" data-target="#logoutForm">Выход</a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </section>


     <section class="feature" id="feature">
        <div class="container">
            <div class="row">

                <div class="d-flex flex-column justify-content-center ml-lg-auto mr-lg-5 col-lg-5 col-md-6 col-12">
                    <h3 class="mb-3 text-white" data-aos="fade-up">Вы еще не с нами?</h3>

                    <h6 class="mb-4 text-white" data-aos="fade-up">Вы можете зарегистрироваться у нас на сайте или войти под учетной записью другой соцсети</h6>

                    <p data-aos="fade-up" data-aos-delay="200">Так же, пользователи вошедшие под учетной записью на сайт могут оставлять свои комментарии!</p>
                    {% if user.is_authenticated %}
                        {% UserReviewText user as reviewtext %}
                        {% if reviewtext %}
                            <a href="#" class="btn custom-btn bg-color mt-3" data-aos="fade-up" data-aos-delay="300" data-toggle="modal" data-target="#reviewForm">Редактировать свой отзыв</a>
                        {% else %}
                            <a href="#" class="btn custom-btn bg-color mt-3" data-aos="fade-up" data-aos-delay="300" data-toggle="modal" data-target="#reviewForm">Оставить отзыв</a>
                        {% endif %}
                    {% endif %}
                </div>

                <div class="mr-lg-auto mt-3 col-lg-4 col-md-6 col-12">
                     <div class="about-working-hours">
                          <div>

                                <h3 class="mb-4 text-white" data-aos="fade-up" data-aos-delay="500">График работы:</h3>

                                  <strong class="d-block" data-aos="fade-up" data-aos-delay="600">Если <span style="color: red">есть</span> работа</strong>

                                <p data-aos="fade-up" data-aos-delay="800">9:00 - 21:00</p>

                                <strong class="mt-3 d-block" data-aos="fade-up" data-aos-delay="700">Если нету</strong>

                                <p data-aos="fade-up" data-aos-delay="800">выходной</p>
                               </div>
                          </div>
                     </div>
                </div>

            </div>
        </div>
    </section>


     <!-- ABOUT -->
     <section class="about section" id="about">
               <div class="container">
                    <div class="row">

                            <div class="mb-lg-0 mb-4 col-lg-5 col-md-10 mx-auto col-12">
                                <h2 class="mb-4" data-aos="fade-up" data-aos-delay="300">Чем мы занимаемся?</h2>

                                <p data-aos="fade-up" data-aos-delay="400">Мы занимаемся ремонтом компьютеров, системным администрированием, настройкой и монтажом компьютерной сети, созданием сайтов для вашего бизнеса,  ремонтом любой РЭА и офисной оргтехники, и заправкой картриджей. У вас не печатает принтер, тупит комп, не включается телевизор или другая РЭА? Не работает ксерокс, вышел из строя плоттер? Вы открыли свой бизнес и хотите организовать регулярное обслуживание и профилактику вашего оборудования?</p>

                                <p data-aos="fade-up" data-aos-delay="500">Мы решим любые задачи по обслуживанию оргтехники, замене, заправке и ремонту картриджей. Если требуется ремонт, мы отремонтируем ваше оборудование на высшем уровне и в кротчайший срок за приемлемую цену!</p>

                            </div>

                            <div class="ml-lg-auto col-lg-3 col-md-6 col-12" data-aos="fade-up" data-aos-delay="700">
                                <div class="team-thumb">
                                    <img src={% static "images/team/team-vitalii.jpg" %} class="img-fluid" alt="Engeneer">

                                    <div class="team-info d-flex flex-column">

                                        <h3>Виталий</h3>
                                        <span>Мегазаправщик</span>

{#                                        <ul class="social-icon mt-3">#}
{#                                            <li><a href="#" class="fa fa-twitter"></a></li>#}
{#                                            <li><a href="#" class="fa fa-instagram"></a></li>#}
{#                                        </ul>#}
                                    </div>
                                </div>

                            </div>

                    </div>
               </div>
     </section>

    <section>
        {% include 'flat/review.html' %}
    </section>

     <!-- CLASS -->
     <section class="class section" id="services">

               <div class="container">
                    <div class="row">

                        <div class="col-lg-12 col-12 text-center mb-5">
                            <h6 data-aos="fade-up">Мы можем многое</h6>

                            <h2 class="text-muted" data-aos="fade-up" data-aos-delay="200">Наш спектр услуг</h2>
                        </div>

                        {% showAllActiveCarouselItems as items %}

                        <div class="owl-carousel owl-theme">
                            {% for item in items %}

                              <div class="card item" data-aos="fade-up" data-aos-delay="{{ item.delay }}">
                                    <img class="card-img-top" src="{{ item.image.url }}" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                                    <div class="card-body">
                                      <h5 class="card-title">{{ item.title }}</h5>
                                      <p class="card-text">{{ item.description }}</p>
                                    </div>
                              </div>

                            {% endfor %}
                        </div>

                    </div>
               </div>
     </section>

     <!-- CONTACTы -->
     <section class="contact section" id="contacts">
          <div class="container">
               <div class="row">

                    <div class="ml-auto col-lg-5 col-md-6 col-12">
                        <h2 class="mb-4 pb-2" data-aos="fade-up" data-aos-delay="200">Напишите мне:</h2>

                        <form name="mailform" action="{% url 'sendmail' %}" method="POST" class="contact-form webform" data-aos="fade-up" data-aos-delay="400" role="form">
                            {% csrf_token %}
                            <input type="text" class="form-control" name="cf-name" placeholder="Ваше имя" required>

                            <input type="email" class="form-control" name="cf-email" placeholder="Ваш Email" required>

                            <textarea class="form-control" rows="5" name="cf-message" placeholder="Текст сообщения" required></textarea>

                            <button type="submit" class="form-control" id="submit-mail" name="submit">Отправить</button>
                        </form>
                    </div>

                    <div class="mx-auto mt-4 mt-lg-0 mt-md-0 col-lg-5 col-md-6 col-12">
                        <h2 class="mb-4" data-aos="fade-up" data-aos-delay="600">Где меня искать:</h2>

                        <div class="d-flex flex-column justify-content-start mx-auto col-12">
                            <a class="mb-3 text-muted" href="tel:+375293645690" data-aos="fade-up" data-aos-delay="600"><i class="fa fa-phone mr-1"></i> +375 (29) 364-56-90</a>
                            <a class="mb-3 text-muted" href="mailto:yurevich_vital@mail.ru?subject=TMV service" data-aos="fade-up" data-aos-delay="700"><i class="fa fa-envelope-o mr-1"></i> yurevich_vital@mail.ru</a>
                            <a class="text-muted" data-aos="fade-up" data-aos-delay="800"><i class="fa fa-map-marker mr-1"></i> Минск ул. Наполеона Орды 39</a>
                        </div>

{#<!-- How to change your own map point#}
{#	1. Go to Google Maps#}
{#	2. Click on your location point#}
{#	3. Click "Share" and choose "Embed map" tab#}
{#	4. Copy only URL and paste it within the src="" field below#}
{#-->#}
                        <div class="google-map mt-1 pt-3" data-aos="fade-up" data-aos-delay="900">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4707.415519875455!2d27.48388224226997!3d53.84806152633883!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbd08be52487f7%3A0x1179e43f3dfd5270!2z0YPQuy4g0J3QsNC_0L7Qu9C10L7QvdCwINCe0YDQtNGLIDM5LCDQnNC40L3RgdC6!5e0!3m2!1sru!2sby!4v1600258997254!5m2!1sru!2sby" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        </div>
                    </div>
                    
               </div>
          </div>
     </section>


     <!-- FOOTER -->
     <footer class="site-footer">
          <div class="container">
               <div class="row d-flex">

                    <div class="col-lg-5 col-md-5">
                        <p class="copyright-text">Copyright &copy; 2020 TMV Co.
                    </div>

               </div>
          </div>
     </footer>

     <!-- SCRIPTS -->
     <script src={% static "js/jquery.min.js" %}></script>
     <script src={% static "js/bootstrap.min.js" %}></script>
     <script src={% static "js/aos.js" %}></script>
     <script src={% static "js/smoothscroll.js" %}></script>
     <script src={% static "js/owl.carousel.min.js" %}></script>
     <script src={% static "js/custom.js" %}></script>

{% endblock %}

templates/flat/modal_auth.html
{% load auth_base_tags i18n account socialaccount %}
{% loadLoginForm as loginform %}

<!-- Modal -->
    <div class="modal fade" id="signinForm" tabindex="-1" role="dialog" aria-labelledby="signinFormLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">

        <div class="modal-content">
          <div class="modal-header">

            <h2 class="modal-title" id="signinFormLabel">Войти на сайт</h2>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
              <form class="login" method="POST" action="{% url 'account_login' %}">
                  {% csrf_token %}
{#                  {{ loginform.as_p }}#}
                  <input id="id_login" type="text" class="form-control" name="login" autofocus="autofocus" placeholder="Login или Email" maxlength="150" required>
                  <input type="password" name="password" placeholder="Пароль" required id="id_password" class="form-control">

                  {% if redirect_field_value %}
                  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                  {% endif %}

                  <button id="submit-auth" class="form-control" type="submit" name="submit">{% trans "Sign In" %}</button>
                    <div class="custom-control custom-checkbox d-flex justify-content-between flex-wrap">
                        <input type="checkbox" class="custom-control-input" name="remember" id="id_remember">
                        <label class="custom-control-label text-small text-muted" for="id_remember">Запомнить меня</label>
                        <a class="button secondaryAction text-small" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
                    </div>
              </form>
            <form class="membership-form webform" role="form">
          </div>
          <div class="modal-body">
              {% get_providers as socialaccount_providers %}
           {% if socialaccount_providers %}
               <hr>
               <div class="d-flex justify-content-around">
               {% for provider in socialaccount_providers %}
                       {% if provider.id == "openid" %}
                           {% for brand in provider.get_brands %}
                               <a title="{{brand.name}}"
                                  class="socialaccount_provider fab fa-{{provider.id}} {{brand.id}}"
                                  href="{% provider_login_url provider.id openid=brand.openid_url process=process %}"
                               ></a>
                           {% endfor %}
                       {% endif %}
                       <a title="Авторизация через {{provider.name}}" class="socialaccount_provider fab fa-{{provider.id}}" style="font-size: 32px;"
                          href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}"></a>
               {% endfor %}
               </div>
           {% endif %}
          </div>

        </div>
      </div>
    </div>

templates/flat/modal_logout.html
{% load i18n %}
<!-- sign up Modal -->
    <div class="modal fade" id="logoutForm" tabindex="-1" role="dialog" aria-labelledby="logoutLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">

        <div class="modal-content">
          <div class="modal-header">

            <h2 class="modal-title" id="logoutLabel"></h2>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
              <h6>{% trans 'Are you sure you want to sign out?' %}</h6>

                <form method="post" action="{% url 'account_logout' %}">
                  {% csrf_token %}
                  {% if redirect_field_value %}
                  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                  {% endif %}
                  <button id="submit-logout" class="form-control" type="submit" name="submit">{% trans "Sign Out" %}</button>
                </form>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

templates/flat/modal_review.html
{% load content_tags %}
{% UserReviewText user as reviewtext %}
<!-- user review Modal -->
    <div class="modal fade" id="reviewForm" tabindex="-1" role="dialog" aria-labelledby="reviewLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">

        <div class="modal-content">
          <div class="modal-header">

            <h2 class="modal-title" id="reviewLabel">Оставить отзыв</h2>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
              <h6>Что вы о нас думаете</h6>
                <form method="post" action="{% url 'sendreview' %}">
                    {% csrf_token %}

                    <input hidden readonly name="sendername" required id="id_sendername" value="{{ user.id }}">
                    <textarea class="form-control" name="review" cols="40" rows="10" maxlength="999" required id="id_review">{% if reviewtext %}{{ reviewtext }}{% endif %}</textarea>
                    <button id="submit-review" class="form-control" type="submit" name="submit">{% if reviewtext %}Изменить{% else %}Оставить{% endif %}</button>


                </form>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

templates/flat/modal_signup.html
<!-- sign up Modal -->
{% load i18n %}
    <div class="modal fade" id="signupForm" tabindex="-1" role="dialog" aria-labelledby="signupFormLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">

        <div class="modal-content">
          <div class="modal-header">

            <h2 class="modal-title" id="signupFormLabel">Регистрация</h2>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">

            <form action=""></form>
            <form action="{% url 'account_signup' %}" method="POST">
                {% csrf_token %}
                <input class="form-control" type="text" name="username" placeholder="Ваш логин" autofocus="autofocus" minlength="1" maxlength="150" required="" id="id_username">

                <input class="form-control" type="email" name="email" placeholder="E-mail адрес" id="id_email">

                <input class="form-control" type="password" name="password1" placeholder="Пароль" required="" id="id_password1">

                <input class="form-control" type="password" name="password2" placeholder="Пароль (ещё раз)" required="" id="id_password2">

                {% if redirect_field_value %}
                  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <button type="submit" class="form-control" id="submit-signup" name="submit">Зарегистрироваться</button>
            </form>
          </div>

          <div class="modal-footer"></div>

        </div>
      </div>
    </div>